project:
  type: book
  output-dir: docs

book:
  title: "Quarto"
  author: "Dr Andrew Young"
  date: last-modified
  chapters:
    - index.qmd
    - geodesics.qmd
    - about.qmd

editor:
  render-on-save: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    citations-hover: true
  pdf:
    documentclass: scrreprt
    lang: en-GB
