project:
  type: book
  output-dir: docs

profile:
  default: prob1ans

book:
  title: "Quarto"
  author: "Dr Andrew Young"
  date: last-modified
  chapters:
    - index.qmd
    - part: "Course notes"
      chapters:
      - geodesics.qmd
    - part: "Problems"
      chapters: 
        - prob_class_1.qmd
    - about.qmd
  downloads: pdf

editor:
  render-on-save: true

format:
  html:
    css: styles.css
    theme:
      light: flatly
      dark: darkly
    citations-hover: true
  pdf:
    documentclass: scrreprt
    lang: en-GB
